server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=0
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/transactions/**
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts/**
          filters:
            - AddRequestHeader=Content-Type, application/json
        - id: debit-card-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/debit-cards/**
          filters:
            - AddRequestHeader=Content-Type, application/json
        - id: credit-service-route
          uri: lb://CREDIT-SERVICE
          predicates:
            - Path=/api/credits/**
          filters:
            - AddRequestHeader=Content-Type, application/json
        - id: credit-cards-route
          uri: lb://CREDIT-SERVICE
          predicates:
            - Path=/api/credit-cards/**
          filters:
            - AddRequestHeader=Content-Type, application/json
        - id: credit-customer-eligibility
          uri: lb://CREDIT-SERVICE
          predicates:
            - Path=/api/customer-eligibility/**
          filters:
            - AddRequestHeader=Content-Type, application/json
        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/api/reports/**
        - id: yanki-service
          uri: lb://YANKI-SERVICE
          predicates:
            - Path=/api/yanki/**
        - id: bootcoin-service-user
          uri: lb://BOOTCOIN-SERVICE
          predicates:
            - Path=/api/bootcoin/user/**
          filters:
            - PreserveHostHeader
            - name: RewritePath
              args:
                regexp: /api/bootcoin/user/(?<remaining>.*)
                replacement: /api/bootcoin/user/${remaining}
        - id: bootcoin-service-purchase
          uri: lb://BOOTCOIN-SERVICE
          predicates:
            - Path=/api/bootcoin/purchases/**
          filters:
            - PreserveHostHeader
            - name: RewritePath
              args:
                regexp: /api/bootcoin/purchases/(?<remaining>.*)
                replacement: /api/bootcoin/purchases/${remaining}
        - id: bootcoin-service-exchange
          uri: lb://BOOTCOIN-SERVICE
          predicates:
            - Path=/api/bootcoin/exchange-rate/**
          filters:
            - PreserveHostHeader
            - name: RewritePath
              args:
                regexp: /api/bootcoin/exchange-rate/(?<remaining>.*)
                replacement: /api/bootcoin/exchange-rate/${remaining}
        - id: bootcoin-service-bank
          uri: lb://BOOTCOIN-SERVICE
          predicates:
            - Path=/api/bootcoin/transaction-bank/**
          filters:
            - PreserveHostHeader
            - name: RewritePath
              args:
                regexp: /api/bootcoin/transaction-bank/(?<remaining>.*)
                replacement: /api/bootcoin/transaction-bank/${remaining}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-cxgjf0gxbhbsfccz.canadacentral-01.azurewebsites.net/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    reactor.netty.http.client: DEBUG